name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you intend to publish the app to pub.dev.

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  url_launcher: ^6.1.5 
  font_awesome_flutter: ^10.3.0  # Adicionando a biblioteca Font Awesome

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/logoapp.png
    - assets/imagens/logoappinicio.png
    - assets/imagens/icongoogle.png
    - assets/imagens/fumar.jpg
    - assets/imagens/beber.jpg
    - assets/imagens/drogas.jpg
    - assets/imagens/bulimia.jpg
    - assets/imagens/pornografia.jpg
    - assets/imagens/clinica1.jpg
    - assets/imagens/clinica2.jpg
    - assets/imagens/clinica3.jpg
    - assets/imagens/clinica4.jpg


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: LemonMilk
      fonts:
        - asset: assets/fonts/LemonMilk-Bold.otf
