name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you intend to publish the app to pub.dev.

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Downgraded as suggested
  http: ^1.2.2  # Corrigido para a versão disponível
  flutter_svg: ^2.0.10+1  # Atualizado
  pin_code_fields: ^8.0.1  # Atualizado
  firebase_core: ^3.6.0  # Verifique se necessário
  firebase_auth: ^5.3.0  # Verifique se necessário
  cloud_firestore: ^5.4.4  # Ajuste a versão para a recomendada
  url_launcher: ^6.1.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Atualizado

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/logoapp.png
    - assets/imagens/logoappinicio.png
    - assets/imagens/icongoogle.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: LemonMilk
      fonts:
        - asset: assets/fonts/LemonMilk-Bold.otf